{{toYaml cfg}}
output.elasticsearch.username: 'admin'
output.elasticsearch.password: 'admin'

#output.elasticsearch.username: {{bind.elasticsearch.first.cfg.admin_username}}
#output.elasticsearch.password: {{bind.elasticsearch.first.cfg.admin_password}}
